project 'Restroom.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Restroom' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google/Analytics'
  # Pods for Restroom

  target 'RestroomTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RestroomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


