//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Trips = new HashSet<Trip>();
            this.TripPatterns = new HashSet<TripPattern>();
            this.VehicleDisplayCodes = new HashSet<VehicleDisplayCode>();
            this.Blocks = new HashSet<Block>();
            this.TripStopsToday = new HashSet<TripStopsToday>();
        }
    
        public string BookingId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
        public long SysRecNo { get; set; }
        public string BookingDesc { get; set; }
    
        public virtual ICollection<Trip> Trips { get; set; }
        public virtual ICollection<TripPattern> TripPatterns { get; set; }
        public virtual ICollection<VehicleDisplayCode> VehicleDisplayCodes { get; set; }
        public virtual ICollection<Block> Blocks { get; set; }
        public virtual ICollection<TripStopsToday> TripStopsToday { get; set; }
    }
}
