//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupancyPrediction
    {
        public int OccupancyPredictionId { get; set; }
        public string BookingId { get; set; }
        public string RouteAlpha { get; set; }
        public string Direction { get; set; }
        public string DayOfWeek { get; set; }
        public string TripNumberCadAvl { get; set; }
        public Nullable<int> TripNumberHastus { get; set; }
        public string StopIdCadAvl { get; set; }
        public string Id511 { get; set; }
        public Nullable<System.TimeSpan> AvgTimeStopDeparture { get; set; }
        public Nullable<decimal> AvgApcLastThreeRuns { get; set; }
        public Nullable<decimal> AvgApcAllRuns { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDatetime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
        public Nullable<short> AvgVehicleCapacity { get; set; }
    }
}
