//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripStopsToday
    {
        public int TripStopsTodayId { get; set; }
        public string BookingId { get; set; }
        public string RouteAlpha { get; set; }
        public int DirectionId { get; set; }
        public string Direction { get; set; }
        public string ScheduleType { get; set; }
        public string TripHeadsign { get; set; }
        public string PatternDestination { get; set; }
        public string PatternDestinationJoined { get; set; }
        public int PatternId { get; set; }
        public System.DateTime TripStartTime { get; set; }
        public int PositionNumber { get; set; }
        public System.DateTime PassingTime { get; set; }
        public int Id511 { get; set; }
        public string PlaceId { get; set; }
        public int TripNumberHastus { get; set; }
        public int TripNumberCadAvl { get; set; }
        public string StopNumberHastus { get; set; }
        public int StopNumberCadAvl { get; set; }
        public string StopDescription { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
        public decimal StopLongitude { get; set; }
        public decimal StopLatitude { get; set; }
        public Nullable<int> RouteVarID { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
