//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waypoints
    {
        public string Booking { get; set; }
        public string RouteAlpha { get; set; }
        public Nullable<int> RouteVarID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<float> Heading { get; set; }
        public Nullable<int> DistanceToNextStop { get; set; }
        public Nullable<int> DistanceFromStart { get; set; }
        public Nullable<int> StopSequence { get; set; }
        public int Direction { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public string DirectionName { get; set; }
        public string PatternDestinationJoined { get; set; }
        public int VersionID { get; set; }
        public long WaypointsId { get; set; }
        public string FirstPlaceId { get; set; }
        public string LastPlaceId { get; set; }
    }
}
