//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.DataAccess.Scheduling
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using ACTransit.Entities.Scheduling;
    
    public partial class SchedulingEntities : DbContext
    {
        public SchedulingEntities()
            : base("name=SchedulingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteList> RouteLists { get; set; }
        public virtual DbSet<RouteType> RouteTypes { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripPattern> TripPatterns { get; set; }
        public virtual DbSet<TripStop> TripStops { get; set; }
        public virtual DbSet<TripTimingPoint> TripTimingPoints { get; set; }
        public virtual DbSet<StopDistrict> StopDistricts { get; set; }
        public virtual DbSet<VehicleDisplayCode> VehicleDisplayCodes { get; set; }
        public virtual DbSet<ScheduleDeparture> ScheduleDepartures { get; set; }
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<TripStopsToday> TripStopsToday { get; set; }
        public virtual DbSet<Waypoints> Waypoints { get; set; }
        public virtual DbSet<ActiveStops> ActiveStops { get; set; }
        public virtual DbSet<AllStops> AllStops { get; set; }
        public virtual DbSet<RouteProfile> RouteProfile { get; set; }
        public virtual DbSet<OccupancyPrediction> OccupancyPrediction { get; set; }
    
        public virtual ObjectResult<NearestStop_Result> NearestStop(Nullable<decimal> lat, Nullable<decimal> @long, Nullable<int> top, Nullable<bool> isPublic, Nullable<bool> allowAlighting, Nullable<bool> allowBoarding, string corner, Nullable<bool> isBart, Nullable<bool> isTransitCenter, Nullable<bool> isInService, Nullable<bool> isGPSValidated, Nullable<bool> avaStatus)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(decimal));
    
            var longParameter = @long.HasValue ?
                new ObjectParameter("Long", @long) :
                new ObjectParameter("Long", typeof(decimal));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            var isPublicParameter = isPublic.HasValue ?
                new ObjectParameter("IsPublic", isPublic) :
                new ObjectParameter("IsPublic", typeof(bool));
    
            var allowAlightingParameter = allowAlighting.HasValue ?
                new ObjectParameter("AllowAlighting", allowAlighting) :
                new ObjectParameter("AllowAlighting", typeof(bool));
    
            var allowBoardingParameter = allowBoarding.HasValue ?
                new ObjectParameter("AllowBoarding", allowBoarding) :
                new ObjectParameter("AllowBoarding", typeof(bool));
    
            var cornerParameter = corner != null ?
                new ObjectParameter("Corner", corner) :
                new ObjectParameter("Corner", typeof(string));
    
            var isBartParameter = isBart.HasValue ?
                new ObjectParameter("IsBart", isBart) :
                new ObjectParameter("IsBart", typeof(bool));
    
            var isTransitCenterParameter = isTransitCenter.HasValue ?
                new ObjectParameter("IsTransitCenter", isTransitCenter) :
                new ObjectParameter("IsTransitCenter", typeof(bool));
    
            var isInServiceParameter = isInService.HasValue ?
                new ObjectParameter("IsInService", isInService) :
                new ObjectParameter("IsInService", typeof(bool));
    
            var isGPSValidatedParameter = isGPSValidated.HasValue ?
                new ObjectParameter("IsGPSValidated", isGPSValidated) :
                new ObjectParameter("IsGPSValidated", typeof(bool));
    
            var avaStatusParameter = avaStatus.HasValue ?
                new ObjectParameter("AvaStatus", avaStatus) :
                new ObjectParameter("AvaStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NearestStop_Result>("NearestStop", latParameter, longParameter, topParameter, isPublicParameter, allowAlightingParameter, allowBoardingParameter, cornerParameter, isBartParameter, isTransitCenterParameter, isInServiceParameter, isGPSValidatedParameter, avaStatusParameter);
        }
    
        public virtual ObjectResult<GetStopsWithinProximity_Result> GetStopsWithinProximity(Nullable<double> originatingLatitude, Nullable<double> originatingLongitude, string unitOfMeasure, Nullable<double> distance, string routeName)
        {
            var originatingLatitudeParameter = originatingLatitude.HasValue ?
                new ObjectParameter("OriginatingLatitude", originatingLatitude) :
                new ObjectParameter("OriginatingLatitude", typeof(double));
    
            var originatingLongitudeParameter = originatingLongitude.HasValue ?
                new ObjectParameter("OriginatingLongitude", originatingLongitude) :
                new ObjectParameter("OriginatingLongitude", typeof(double));
    
            var unitOfMeasureParameter = unitOfMeasure != null ?
                new ObjectParameter("UnitOfMeasure", unitOfMeasure) :
                new ObjectParameter("UnitOfMeasure", typeof(string));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            var routeNameParameter = routeName != null ?
                new ObjectParameter("RouteName", routeName) :
                new ObjectParameter("RouteName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStopsWithinProximity_Result>("GetStopsWithinProximity", originatingLatitudeParameter, originatingLongitudeParameter, unitOfMeasureParameter, distanceParameter, routeNameParameter);
        }
    
        public virtual ObjectResult<GetRoutes_Result> GetRoutes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRoutes_Result>("GetRoutes");
        }
    
        public virtual int AddBooking(string newBookingId, string addUserId)
        {
            var newBookingIdParameter = newBookingId != null ?
                new ObjectParameter("NewBookingId", newBookingId) :
                new ObjectParameter("NewBookingId", typeof(string));
    
            var addUserIdParameter = addUserId != null ?
                new ObjectParameter("AddUserId", addUserId) :
                new ObjectParameter("AddUserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddBooking", newBookingIdParameter, addUserIdParameter);
        }
    
        public virtual ObjectResult<GetTripInfo_Result> GetTripInfo(Nullable<int> tripNumber)
        {
            var tripNumberParameter = tripNumber.HasValue ?
                new ObjectParameter("TripNumber", tripNumber) :
                new ObjectParameter("TripNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTripInfo_Result>("GetTripInfo", tripNumberParameter);
        }
    
        public virtual ObjectResult<GetDepartures_Result> GetDepartures(Nullable<System.DateTime> startDate, string originStopIds, string routes)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var originStopIdsParameter = originStopIds != null ?
                new ObjectParameter("OriginStopIds", originStopIds) :
                new ObjectParameter("OriginStopIds", typeof(string));
    
            var routesParameter = routes != null ?
                new ObjectParameter("Routes", routes) :
                new ObjectParameter("Routes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartures_Result>("GetDepartures", startDateParameter, originStopIdsParameter, routesParameter);
        }
    
        public virtual ObjectResult<GetTripStops_Result> GetTripStops(string booking, Nullable<System.DateTime> todayDate, string routeAlpha, string direction, string scheduleType, string stop511)
        {
            var bookingParameter = booking != null ?
                new ObjectParameter("Booking", booking) :
                new ObjectParameter("Booking", typeof(string));
    
            var todayDateParameter = todayDate.HasValue ?
                new ObjectParameter("TodayDate", todayDate) :
                new ObjectParameter("TodayDate", typeof(System.DateTime));
    
            var routeAlphaParameter = routeAlpha != null ?
                new ObjectParameter("RouteAlpha", routeAlpha) :
                new ObjectParameter("RouteAlpha", typeof(string));
    
            var directionParameter = direction != null ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(string));
    
            var scheduleTypeParameter = scheduleType != null ?
                new ObjectParameter("ScheduleType", scheduleType) :
                new ObjectParameter("ScheduleType", typeof(string));
    
            var stop511Parameter = stop511 != null ?
                new ObjectParameter("Stop511", stop511) :
                new ObjectParameter("Stop511", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTripStops_Result>("GetTripStops", bookingParameter, todayDateParameter, routeAlphaParameter, directionParameter, scheduleTypeParameter, stop511Parameter);
        }
    
        public virtual ObjectResult<GetStopsWithOrder_Result> GetStopsWithOrder(string booking, string routeAlphas, string direction, string destination, string scheduleType)
        {
            var bookingParameter = booking != null ?
                new ObjectParameter("Booking", booking) :
                new ObjectParameter("Booking", typeof(string));
    
            var routeAlphasParameter = routeAlphas != null ?
                new ObjectParameter("RouteAlphas", routeAlphas) :
                new ObjectParameter("RouteAlphas", typeof(string));
    
            var directionParameter = direction != null ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            var scheduleTypeParameter = scheduleType != null ?
                new ObjectParameter("ScheduleType", scheduleType) :
                new ObjectParameter("ScheduleType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStopsWithOrder_Result>("GetStopsWithOrder", bookingParameter, routeAlphasParameter, directionParameter, destinationParameter, scheduleTypeParameter);
        }
    
        public virtual ObjectResult<GetRouteDateExceptions_Result> GetRouteDateExceptions(string bookingId, string routeAlpha)
        {
            var bookingIdParameter = bookingId != null ?
                new ObjectParameter("BookingId", bookingId) :
                new ObjectParameter("BookingId", typeof(string));
    
            var routeAlphaParameter = routeAlpha != null ?
                new ObjectParameter("RouteAlpha", routeAlpha) :
                new ObjectParameter("RouteAlpha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRouteDateExceptions_Result>("GetRouteDateExceptions", bookingIdParameter, routeAlphaParameter);
        }
    
        public virtual ObjectResult<GetRouteStops_Result> GetRouteStops(string booking, string routeAlphas, string direction, string destination, string scheduleType)
        {
            var bookingParameter = booking != null ?
                new ObjectParameter("Booking", booking) :
                new ObjectParameter("Booking", typeof(string));
    
            var routeAlphasParameter = routeAlphas != null ?
                new ObjectParameter("RouteAlphas", routeAlphas) :
                new ObjectParameter("RouteAlphas", typeof(string));
    
            var directionParameter = direction != null ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            var scheduleTypeParameter = scheduleType != null ?
                new ObjectParameter("ScheduleType", scheduleType) :
                new ObjectParameter("ScheduleType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRouteStops_Result>("GetRouteStops", bookingParameter, routeAlphasParameter, directionParameter, destinationParameter, scheduleTypeParameter);
        }
    
        public virtual ObjectResult<GetTripScheduleInfo_Result> GetTripScheduleInfo(string booking, string routeAlphas, string direction, string destination, string scheduleType, Nullable<bool> hasAllStops, string stop511)
        {
            var bookingParameter = booking != null ?
                new ObjectParameter("Booking", booking) :
                new ObjectParameter("Booking", typeof(string));
    
            var routeAlphasParameter = routeAlphas != null ?
                new ObjectParameter("RouteAlphas", routeAlphas) :
                new ObjectParameter("RouteAlphas", typeof(string));
    
            var directionParameter = direction != null ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            var scheduleTypeParameter = scheduleType != null ?
                new ObjectParameter("ScheduleType", scheduleType) :
                new ObjectParameter("ScheduleType", typeof(string));
    
            var hasAllStopsParameter = hasAllStops.HasValue ?
                new ObjectParameter("HasAllStops", hasAllStops) :
                new ObjectParameter("HasAllStops", typeof(bool));
    
            var stop511Parameter = stop511 != null ?
                new ObjectParameter("Stop511", stop511) :
                new ObjectParameter("Stop511", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTripScheduleInfo_Result>("GetTripScheduleInfo", bookingParameter, routeAlphasParameter, directionParameter, destinationParameter, scheduleTypeParameter, hasAllStopsParameter, stop511Parameter);
        }
    
        public virtual ObjectResult<GetScheduledTrips_Result> GetScheduledTrips(string booking, Nullable<int> tripStartTimeOffsetMinutes, Nullable<int> tripEndTimeOffsetMinutes)
        {
            var bookingParameter = booking != null ?
                new ObjectParameter("Booking", booking) :
                new ObjectParameter("Booking", typeof(string));
    
            var tripStartTimeOffsetMinutesParameter = tripStartTimeOffsetMinutes.HasValue ?
                new ObjectParameter("TripStartTimeOffsetMinutes", tripStartTimeOffsetMinutes) :
                new ObjectParameter("TripStartTimeOffsetMinutes", typeof(int));
    
            var tripEndTimeOffsetMinutesParameter = tripEndTimeOffsetMinutes.HasValue ?
                new ObjectParameter("TripEndTimeOffsetMinutes", tripEndTimeOffsetMinutes) :
                new ObjectParameter("TripEndTimeOffsetMinutes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScheduledTrips_Result>("GetScheduledTrips", bookingParameter, tripStartTimeOffsetMinutesParameter, tripEndTimeOffsetMinutesParameter);
        }
    
        public virtual ObjectResult<GetVehicleOccupancy_Result> GetVehicleOccupancy(string vehicleIds)
        {
            var vehicleIdsParameter = vehicleIds != null ?
                new ObjectParameter("VehicleIds", vehicleIds) :
                new ObjectParameter("VehicleIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVehicleOccupancy_Result>("GetVehicleOccupancy", vehicleIdsParameter);
        }
    }
}
